import os
import time
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support, accuracy_score

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR

# Import your model architecture from model.py
from model import build_model

# ==============================================================================
# CONFIGURATION & HYPERPARAMETERS
# ==============================================================================
MANIFEST_CSV = "./dataset_manifest.csv"  # Path to manifest CSV generated by prepare_dataset.py
SAVE_DIR = "./checkpoints"              # Directory to save trained model weights
BATCH_SIZE = 32                         # Batch size (adjust based on GPU VRAM)
NUM_EPOCHS = 25                         # Total training epochs
LEARNING_RATE = 1e-3                    # Initial learning rate
WEIGHT_DECAY = 1e-4                     # AdamW weight decay
VAL_SIZE = 0.2                          # 20% validation split
RANDOM_SEED = 42                        # Seed for reproducible train/val splits
NUM_WORKERS = 4                         # DataLoader CPU worker threads
THRESHOLD = 0.5                         # Decision threshold for hazard detection


# ==============================================================================
# PYTORCH DATASET CLASS
# ==============================================================================
class PhotosensitiveDataset(Dataset):
    """
    PyTorch Dataset that loads pre-saved (16, 3, 224, 224) numpy tensors 
    and multi-label binary targets [flicker_label, illusion_label].
    """
    def __init__(self, df_manifest):
        self.df = df_manifest.reset_index(drop=True)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        
        # Load preprocessed tensor chunk: Shape (16, 3, 224, 224)
        tensor_array = np.load(row['tensor_path']).astype(np.float32)
        tensor = torch.from_numpy(tensor_array)
        
        # Multi-label target vector: [flicker_label, illusion_label]
        labels = np.array([row['flicker_label'], row['illusion_label']], dtype=np.float32)
        target = torch.from_numpy(labels)
        
        return tensor, target


# ==============================================================================
# METRIC EVALUATION HELPER
# ==============================================================================
def calculate_metrics(y_true, y_pred_probs, threshold=0.5):
    """
    Calculates multi-label accuracy, precision, recall, and F1-score.
    """
    y_pred = (y_pred_probs >= threshold).astype(int)
    
    # Subset accuracy (exact match across both outputs)
    exact_match_acc = accuracy_score(y_true, y_pred)
    
    # Class-wise precision, recall, F1
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average=None, zero_division=0
    )
    
    # Mean macro F1
    macro_f1 = np.mean(f1)
    
    return {
        'exact_acc': exact_match_acc,
        'macro_f1': macro_f1,
        'flicker_f1': f1[0],
        'flicker_prec': precision[0],
        'flicker_rec': recall[0],
        'illusion_f1': f1[1],
        'illusion_prec': precision[1],
        'illusion_rec': recall[1],
    }


# ==============================================================================
# TRAIN & VALIDATION LOOPS
# ==============================================================================
def train_one_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    all_targets = []
    all_probs = []

    for inputs, targets in dataloader:
        inputs = inputs.to(device)   # Shape: (B, 16, 3, 224, 224)
        targets = targets.to(device) # Shape: (B, 2)

        optimizer.zero_grad()

        # Forward pass
        logits = model(inputs)
        loss = criterion(logits, targets)

        # Backward pass & Optimization
        loss.backward()
        optimizer.step()

        # Track statistics
        running_loss += loss.item() * inputs.size(0)
        probs = torch.sigmoid(logits).detach().cpu().numpy()
        
        all_probs.append(probs)
        all_targets.append(targets.cpu().numpy())

    epoch_loss = running_loss / len(dataloader.dataset)
    all_probs = np.vstack(all_probs)
    all_targets = np.vstack(all_targets)
    
    metrics = calculate_metrics(all_targets, all_probs, threshold=THRESHOLD)
    metrics['loss'] = epoch_loss
    return metrics


@torch.no_grad()
def validate(model, dataloader, criterion, device):
    model.eval()
    running_loss = 0.0
    all_targets = []
    all_probs = []

    for inputs, targets in dataloader:
        inputs = inputs.to(device)
        targets = targets.to(device)

        logits = model(inputs)
        loss = criterion(logits, targets)

        running_loss += loss.item() * inputs.size(0)
        probs = torch.sigmoid(logits).cpu().numpy()

        all_probs.append(probs)
        all_targets.append(targets.cpu().numpy())

    epoch_loss = running_loss / len(dataloader.dataset)
    all_probs = np.vstack(all_probs)
    all_targets = np.vstack(all_targets)

    metrics = calculate_metrics(all_targets, all_probs, threshold=THRESHOLD)
    metrics['loss'] = epoch_loss
    return metrics


# ==============================================================================
# MAIN TRAINING EXECUTION
# ==============================================================================
def main():
    # 1. Setup execution device and save paths
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Executing training on Device: {device}")
    
    save_path = Path(SAVE_DIR)
    save_path.mkdir(parents=True, exist_ok=True)

    # 2. Load dataset manifest & perform train/val split
    if not os.path.exists(MANIFEST_CSV):
        raise FileNotFoundError(f"Manifest CSV not found at '{MANIFEST_CSV}'. Run prepare_dataset.py first!")

    manifest_df = pd.read_csv(MANIFEST_CSV)
    print(f"Loaded manifest with {len(manifest_df)} total samples.")

    train_df, val_df = train_test_split(
        manifest_df, test_size=VAL_SIZE, random_state=RANDOM_SEED, shuffle=True
    )
    print(f"Dataset split: {len(train_df)} Training samples | {len(val_df)} Validation samples.")

    # 3. Create PyTorch DataLoaders
    train_dataset = PhotosensitiveDataset(train_df)
    val_dataset = PhotosensitiveDataset(val_df)

    train_loader = DataLoader(
        train_dataset, batch_size=BATCH_SIZE, shuffle=True, 
        num_workers=NUM_WORKERS, pin_memory=True if device.type == 'cuda' else False
    )
    val_loader = DataLoader(
        val_dataset, batch_size=BATCH_SIZE, shuffle=False, 
        num_workers=NUM_WORKERS, pin_memory=True if device.type == 'cuda' else False
    )

    # 4. Instantiate Model, Loss Function, Optimizer, and Scheduler
    print("Building MobileNetV3 + Causal TSM Model...")
    model = build_model(num_classes=2, num_segments=16, pretrained=True).to(device)

    # Multi-label Binary Cross-Entropy with Logits
    criterion = nn.BCEWithLogitsLoss()

    optimizer = AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    scheduler = CosineAnnealingLR(optimizer, T_max=NUM_EPOCHS, eta_min=1e-6)

    # 5. Training Loop
    best_val_f1 = 0.0
    print("\n" + "=" * 80)
    print("STARTING MODEL TRAINING")
    print("=" * 80)

    for epoch in range(1, NUM_EPOCHS + 1):
        start_time = time.time()

        train_metrics = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_metrics = validate(model, val_loader, criterion, device)
        
        scheduler.step()
        elapsed = time.time() - start_time

        # Print Epoch Summary
        print(f"\nEpoch [{epoch:02d}/{NUM_EPOCHS:02d}] ({elapsed:.1f}s) | LR: {scheduler.get_last_lr()[0]:.6f}")
        print(f"  Train -> Loss: {train_metrics['loss']:.4f} | Acc: {train_metrics['exact_acc']*100:.2f}% | Macro F1: {train_metrics['macro_f1']:.4f}")
        print(f"  Val   -> Loss: {val_metrics['loss']:.4f} | Acc: {val_metrics['exact_acc']*100:.2f}% | Macro F1: {val_metrics['macro_f1']:.4f}")
        print(f"  Class Breakdown (Val):")
        print(f"    - Flicker Hazard  -> F1: {val_metrics['flicker_f1']:.4f} | Prec: {val_metrics['flicker_prec']:.4f} | Rec: {val_metrics['flicker_rec']:.4f}")
        print(f"    - Illusion Hazard -> F1: {val_metrics['illusion_f1']:.4f} | Prec: {val_metrics['illusion_prec']:.4f} | Rec: {val_metrics['illusion_rec']:.4f}")

        # Checkpoint Saving: Save best model based on macro validation F1-score
        if val_metrics['macro_f1'] > best_val_f1:
            best_val_f1 = val_metrics['macro_f1']
            best_checkpoint_path = save_path / "best_photosensitive_model.pth"
            
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_metrics': val_metrics,
                'hyperparameters': {
                    'batch_size': BATCH_SIZE,
                    'lr': LEARNING_RATE,
                    'num_segments': 16
                }
            }, best_checkpoint_path)
            
            print(f"  >>> Best model saved! (New Best Val Macro F1: {best_val_f1:.4f})")

    print("\n" + "=" * 80)
    print(f"TRAINING COMPLETE! Best Validation Macro F1-Score: {best_val_f1:.4f}")
    print(f"Model saved to: {save_path / 'best_photosensitive_model.pth'}")
    print("=" * 80)


if __name__ == "__main__":
    main()
